project_name: view-vpa
release:
  github:
    owner: akundrock
    name: view-vpa
builds:
  - id: view-vpa
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/akundrock/view-vpa/pkg/version.version=
archives:
  - id: view-vpa
    builds:
    - view-vpa
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
