apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: view-vpa
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/akundrock/view-vpa/releases/download/v0.1.0/view-vpa_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./view-vpa"
      to: "."
    - from: LICENSE
      to: "."
    bin: "view-vpa"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/akundrock/view-vpa/releases/download/v0.1.0/view-vpa_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./view-vpa"
      to: "."
    - from: LICENSE
      to: "."
    bin: "view-vpa"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/akundrock/view-vpa/releases/download/v0.1.0/view-vpa_windows_amd64.zip
    sha256: ""
    files:
    - from: "/view-vpa.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "view-vpa.exe"
  shortDescription: A new plugin
  homepage: https://github.com/akundrock/view-vpa
  caveats: |
    Usage:
      $ kubectl view-vpa

    For additional options:
      $ kubectl view-vpa --help
      or https://github.com/akundrock/view-vpa/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
